/**
 * DOCX export utility for InkForge novels.
 * Per D-14: DOCX export with heading styles and auto-generated TOC.
 */

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  AlignmentType,
  convertInchesToTwip,
} from 'docx'
import { createProjectDB } from '../db/project-db'
import { getChapters, getChapterNumber } from '../db/chapter-queries'
import { extractTextFromContent } from '../db/chapter-queries'

/**
 * Export steps labels per UI-SPEC.
 */
export const EXPORT_STEPS = {
  PREPARING: '准备导出...',
  GATHERING_CONTENT: '汇总章节内容...',
  GENERATING_FILE: '生成DOCX文件...',
  TRIGGERING_DOWNLOAD: '触发下载...',
} as const

interface ChapterDoc {
  title: string
  content: string
  order: number
}

/**
 * Export all chapters of a project as a DOCX blob.
 * 
 * @param projectId - The project ID to export
 * @param projectTitle - The project title for the document
 * @returns Promise<Blob> - DOCX file blob
 * 
 * Format per D-14:
 * - Book title as title paragraph
 * - Auto-generated TOC (table of contents)
 * - Chapter headings as HeadingLevel.HEADING_1
 * - Chapter content as body paragraphs
 */
export async function exportToDocx(
  projectId: string,
  projectTitle: string
): Promise<Blob> {
  // Step 1: Prepare - open project database
  const db = createProjectDB(projectId)
  
  // Step 2: Gather all chapters
  const chapters = await getChapters(db)
  
  // Step 3: Build document structure
  const children: Paragraph[] = []
  
  // Book title
  children.push(
    new Paragraph({
      text: projectTitle,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 400,
      },
    })
  )
  
  // Table of Contents placeholder
  // Note: TOC generation requires document to be rendered first
  // For a proper TOC, we'd need to use XML manipulation or a TOC field
  children.push(
    new Paragraph({
      text: '目录',
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: {
        before: 600,
        after: 200,
      },
    })
  )
  
  // Add chapter entries to TOC
  for (const chapter of chapters) {
    const chapterNum = getChapterNumber(chapter.order)
    children.push(
      new Paragraph({
        text: `${chapterNum} ${chapter.title}`,
        heading: HeadingLevel.HEADING_2,
        spacing: {
          before: 100,
          after: 50,
        },
      })
    )
  }
  
  // Chapter content sections
  for (const chapter of chapters) {
    const chapterNum = getChapterNumber(chapter.order)
    
    // Chapter heading
    children.push(
      new Paragraph({
        text: `${chapterNum} ${chapter.title}`,
        heading: HeadingLevel.HEADING_1,
        pageBreakBefore: true,
        spacing: {
          before: 400,
          after: 200,
        },
      })
    )
    
    // Chapter content
    if (chapter.content) {
      const text = extractTextFromContent(chapter.content)
      // Split into paragraphs for better formatting
      const paragraphs = text.split(/\n\n+/)
      
      for (const para of paragraphs) {
        if (para.trim()) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: para.trim(),
                  size: 24, // 12pt
                }),
              ],
              spacing: {
                after: 200,
                line: 360, // 1.5 line spacing
              },
            })
          )
        }
      }
    }
  }
  
  // Create document
  const doc = new Document({
    creator: 'InkForge',
    title: projectTitle,
    description: 'Generated by InkForge',
    styles: {
      default: {
        document: {
          run: {
            font: 'SimSun',
            size: 24,
          },
        },
      },
      paragraphStyles: [
        {
          id: 'Heading1',
          name: 'Heading 1',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            size: 36, // 18pt
            bold: true,
          },
          paragraph: {
            spacing: {
              before: 240,
              after: 120,
            },
          },
        },
        {
          id: 'Heading2',
          name: 'Heading 2',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: {
            size: 28, // 14pt
            bold: true,
          },
          paragraph: {
            spacing: {
              before: 200,
              after: 100,
            },
          },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              right: convertInchesToTwip(1.25),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1.25),
            },
          },
        },
        children,
      },
    ],
  })
  
  // Step 4: Generate blob
  const buffer = await Packer.toBuffer(doc)
  return new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  })
}