/**
 * EPUB export utility for InkForge novels.
 * Per D-15: EPUB export with metadata and chapter structure.
 */

import EPub from 'epub-gen'
import { createProjectDB } from '../db/project-db'
import { getChapters, getChapterNumber } from '../db/chapter-queries'
import { extractTextFromContent } from '../db/chapter-queries'

/**
 * Export steps labels per UI-SPEC.
 */
export const EXPORT_STEPS = {
  PREPARING: '准备导出...',
  GATHERING_CONTENT: '汇总章节内容...',
  GENERATING_FILE: '生成EPUB文件...',
  TRIGGERING_DOWNLOAD: '触发下载...',
} as const

export interface EpubMetadata {
  title: string
  author?: string
}

/**
 * Export all chapters of a project as an EPUB blob.
 * 
 * @param projectId - The project ID to export
 * @param metadata - EPUB metadata (title, optional author)
 * @returns Promise<Blob> - EPUB file blob
 * 
 * Format per D-15:
 * - Book title and author in metadata
 * - Chapter list with proper EPUB structure
 * - Standard EPUB content sections
 */
export async function exportToEpub(
  projectId: string,
  metadata: EpubMetadata
): Promise<Blob> {
  // Step 1: Prepare - open project database
  const db = createProjectDB(projectId)
  
  // Step 2: Gather all chapters
  const chapters = await getChapters(db)
  
  // Step 3: Build EPUB structure
  const toc: Array<{ id: string; title: string; data: string }> = []
  
  for (const chapter of chapters) {
    const chapterNum = getChapterNumber(chapter.order)
    const title = `${chapterNum} ${chapter.title}`
    
    // Extract content text
    let content = ''
    if (chapter.content) {
      content = extractTextFromContent(chapter.content)
    }
    
    toc.push({
      id: chapter.id,
      title,
      data: content,
    })
  }
  
  // Create epub options
  const options = {
    // Metadata
    title: metadata.title,
    author: metadata.author || '未知作者',
    publisher: 'InkForge',
    description: 'Generated by InkForge',
    lang: 'zh-CN',
    // Table of contents
    toc: toc,
    // Content CSS (basic styling for readability)
    contentCSS: `
      body {
        font-family: "Noto Sans SC", "SimSun", sans-serif;
        line-height: 1.8;
        text-align: justify;
        margin: 1em;
      }
      h1 {
        text-align: center;
        margin-bottom: 1em;
      }
      p {
        text-indent: 2em;
        margin: 0.5em 0;
      }
    `,
    // Don't write to filesystem - return as buffer
    outputPath: false,
  }
  
  // Generate EPUB
  const book = new EPub(options)
  const epubBuffer = await book.promise
  
  // Step 4: Convert to Blob
  return new Blob([epubBuffer], {
    type: 'application/epub+zip',
  })
}