/**
 * EPUB export utility for InkForge novels.
 * Per D-15: EPUB export with metadata and chapter structure.
 */

import epub from 'epub-gen-memory/bundle'
import { createProjectDB } from '../db/project-db'
import { getChapters, getChapterNumber } from '../db/chapter-queries'
import { extractTextFromContent } from '../db/chapter-queries'

/**
 * Export steps labels per UI-SPEC.
 */
export const EXPORT_STEPS = {
  PREPARING: '准备导出...',
  GATHERING_CONTENT: '汇总章节内容...',
  GENERATING_FILE: '生成EPUB文件...',
  TRIGGERING_DOWNLOAD: '触发下载...',
} as const

export interface EpubMetadata {
  title: string
  author?: string
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

/**
 * Export all chapters of a project as an EPUB blob.
 */
export async function exportToEpub(
  projectId: string,
  metadata: EpubMetadata
): Promise<Blob> {
  const db = createProjectDB(projectId)
  const chapters = await getChapters(db)

  const content = chapters.map((chapter) => {
    const chapterNum = getChapterNumber(chapter.order)
    const title = `${chapterNum} ${chapter.title}`
    const text = chapter.content ? extractTextFromContent(chapter.content) : ''
    const html = text
      .split(/\n+/)
      .filter((p) => p.length > 0)
      .map((p) => `<p>${escapeHtml(p)}</p>`)
      .join('')

    return {
      title,
      content: html || '<p></p>',
    }
  })

  const options = {
    title: metadata.title,
    author: metadata.author || '未知作者',
    publisher: 'InkForge',
    description: 'Generated by InkForge',
    lang: 'zh-CN',
    css: `
      body {
        font-family: "Noto Sans SC", "SimSun", sans-serif;
        line-height: 1.8;
        text-align: justify;
        margin: 1em;
      }
      h1 {
        text-align: center;
        margin-bottom: 1em;
      }
      p {
        text-indent: 2em;
        margin: 0.5em 0;
      }
    `,
  }

  return await epub(options, content)
}
